services:
  nuxt:
    extends:
      file: docker/nuxt/compose.common.yml
      service: nuxt
    build:
      target: develop
    volumes:
      - ./nuxt/src:/app/src:ro
      - ./django/media:/app/src/public/media:ro
      - ./nuxt/eslint.config.mjs:/app/eslint.config.mjs:ro
      - ./nuxt/nuxt.config.ts:/app/nuxt.config.ts:ro
      - ./nuxt/tailwind.config.ts:/app/tailwind.config.ts:ro
      - ./nuxt/tsconfig.json:/app/tsconfig.json:ro
    tmpfs:
      - /tmp
