services:
  nuxt:
    extends:
      file: docker/nuxt/compose.common.yml
      service: nuxt
    build:
      target: develop
    volumes:
      - ./nuxt/app:/app/app
      - ./nuxt/config:/app/config:ro
      - ./nuxt/public:/app/public:ro
      - ./django/media:/app/public/media:ro
      - ./nuxt/eslint.config.ts:/app/eslint.config.ts:ro
      - ./nuxt/nuxt.config.ts:/app/nuxt.config.ts:ro
      - ./nuxt/tsconfig.json:/app/tsconfig.json:ro
    tmpfs:
      - /tmp
