include:
  - path:
    - docker/nginx/compose.prod.yml
    - docker/nuxt/compose.prod.yml
    - docker/django/compose.prod.yml
    - docker/services/umami.yml
    - docker/services/certbot.yml
    - docker/services/backrest.yml
    project_directory: .
