include:
  - path:
    - docker/services/fonts.yml
    project_directory: .

services:
  nginx:
    container_name: wokalek-nginx
    image: wokalek/nginx-brotli:${NGINX_VERSION:?error}
    depends_on:
      - nuxt
      - django
    ports:
      - 80:80
      - 8000:8000
    volumes:
      - ./nginx/conf/dev.conf:/etc/nginx/nginx.conf
      - ./nginx/snippets:/etc/nginx/snippets
      - django-static:/django/static
      - ./django/media:/django/media

  nuxt:
    container_name: wokalek-nuxt
    build:
      dockerfile: docker/nuxt/prod.Dockerfile
      args:
        - NODE_VERSION=${NUXT_NODE_VERSION:?error}
    depends_on:
      fonts:
        condition: service_completed_successfully
    env_file: env/nuxt/.env
    volumes:
      - ./django/media:/nuxt/.output/public/media

  django:
    container_name: wokalek-django
    build:
      dockerfile: docker/django/prod.Dockerfile
      args:
        - PYTHON_VERSION=${DJANGO_PYTHON_VERSION:?error}
    depends_on:
      database:
        condition: service_healthy
    env_file: env/django/.env
    volumes:
      - django-static:/static
      - ./django:/django

  database:
    container_name: wokalek-database
    image: postgres:${DATABASE_POSTGRES_VERSION:?error}
    restart: always
    shm_size: 256mb
    env_file: env/database/.env
    volumes:
      - ./volumes/database/data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready']
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  django-static:
