# Generated by Django 5.0.6 on 2024-07-03 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='image_path',
            field=models.URLField(blank=True, editable=False, null=True, verbose_name='Полный путь до изображения'),
        ),
    ]
