# Generated by Django 5.0.6 on 2024-07-03 19:48

import imagefield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_galleryimage_image_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=imagefield.fields.ImageField(height_field='image_height', upload_to='gallery/image', verbose_name='Изображение', width_field='image_width'),
        ),
    ]
