# Generated by Django 5.0.6 on 2024-07-03 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_gallerysection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallerysection',
            name='code',
        ),
    ]
