# Generated by Django 5.0.6 on 2024-07-03 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0007_galleryimage_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gallery.gallerysection', verbose_name='Раздел'),
        ),
    ]
