# Generated by Django 5.0.6 on 2024-07-03 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0009_remove_galleryimage_section_galleryimage_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleryimage',
            name='section',
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gallery.gallerysection', verbose_name='Раздел'),
        ),
    ]
