# Generated by Django 5.1 on 2024-08-15 16:01

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0001_initial'),
        ('blog', '0001_initial'),
        ('drawings', '0001_initial'),
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
            ],
            options={
                'verbose_name': 'статью',
                'verbose_name_plural': 'статьи',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('articles.article',),
        ),
        migrations.CreateModel(
            name='Drawing',
            fields=[
            ],
            options={
                'verbose_name': 'рисунок',
                'verbose_name_plural': 'рисунки',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('drawings.drawing',),
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
            ],
            options={
                'verbose_name': 'фото',
                'verbose_name_plural': 'фотографии',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('photos.photo',),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
            ],
            options={
                'verbose_name': 'пост',
                'verbose_name_plural': 'посты',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('blog.post',),
        ),
    ]
