# Generated by Django 5.0.7 on 2024-07-11 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articleproxy',
            options={'verbose_name': 'статью', 'verbose_name_plural': 'статьи'},
        ),
        migrations.AlterModelOptions(
            name='postproxy',
            options={'verbose_name': 'пост', 'verbose_name_plural': 'посты'},
        ),
    ]
