# Generated by Django 5.0.7 on 2024-07-11 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_article_options'),
        ('blog', '0003_alter_post_options'),
        ('content', '0002_alter_articleproxy_options_alter_postproxy_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArticleProxy',
        ),
        migrations.DeleteModel(
            name='PostProxy',
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
            ],
            options={
                'verbose_name': 'статью',
                'verbose_name_plural': 'статьи',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('articles.article',),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
            ],
            options={
                'verbose_name': 'пост',
                'verbose_name_plural': 'посты',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('blog.post',),
        ),
    ]
