# Generated by Django 5.0.7 on 2024-08-10 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_photo'),
        ('drawings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drawing',
            fields=[
            ],
            options={
                'verbose_name': 'рисунок',
                'verbose_name_plural': 'рисунки',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('drawings.drawing',),
        ),
    ]
