# Generated by Django 5.0.7 on 2024-07-09 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medialibrary', '0002_image_alt'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_name',
            field=models.CharField(default='123', max_length=100, verbose_name='Имя файла'),
            preserve_default=False,
        ),
    ]
