# Generated by Django 5.0.7 on 2024-07-09 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medialibrary', '0003_image_image_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя файла'),
        ),
    ]
