# Generated by Django 5.0.7 on 2024-07-09 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medialibrary', '0004_alter_image_image_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image_path',
        ),
        migrations.AddField(
            model_name='image',
            name='image_markdown',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='Полный путь до изображения'),
        ),
    ]
