# Generated by Django 5.0.7 on 2024-07-09 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medialibrary', '0005_remove_image_image_path_image_image_markdown'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_markdown',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='Код markdown'),
        ),
    ]
