# Generated by Django 5.0.7 on 2024-07-11 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medialibrary', '0006_alter_image_image_markdown'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': 'изображение', 'verbose_name_plural': 'изображения'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'verbose_name': 'раздел', 'verbose_name_plural': 'разделы'},
        ),
    ]
