services:
  nginx:
    extends:
      file: docker/nginx/compose.common.yml
      service: nginx
    depends_on:
      - nuxt
      - django
      - umami
    ports:
      - 80:80
      - 443:443
    volumes:
      - django_static:/django/static:ro
      - ./nginx/conf/prod.conf:/etc/nginx/nginx.conf:ro
      - ./volumes/nginx/cache:/data/nginx/cache
      - ./volumes/nginx/log:/var/log/nginx
      - ./volumes/certbot/www:/certbot/www
      - ./volumes/certbot/conf/live/wokalek.ru/fullchain.pem:/certbot/certs/fullchain.pem
      - ./volumes/certbot/conf/live/wokalek.ru/privkey.pem:/certbot/certs/privkey.pem
    restart: always
