# Generated by Django 5.0.7 on 2024-08-10 14:32

import django.db.models.deletion
import django.utils.timezone
import imagefield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('update_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'раздел',
                'verbose_name_plural': 'разделы',
            },
        ),
        migrations.CreateModel(
            name='Drawing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('update_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата обновления')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации')),
                ('image', imagefield.fields.ImageField(height_field='image_height', upload_to='drawings', verbose_name='Изображение', width_field='image_width')),
                ('image_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя файла')),
                ('alt', models.CharField(max_length=100, verbose_name='Альтернативный текст')),
                ('image_width', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('image_height', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('image_ppoi', imagefield.fields.PPOIField(default='0.5x0.5', max_length=20)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drawings.section', verbose_name='Раздел')),
            ],
            options={
                'verbose_name': 'рисунок',
                'verbose_name_plural': 'рисунки',
            },
        ),
    ]
