# Generated by Django 5.0.6 on 2024-06-30 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='question_text',
            new_name='text',
        ),
    ]
