# Generated by Django 5.0.7 on 2024-07-11 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_squashed_0002_post_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'пост', 'verbose_name_plural': 'посты'},
        ),
    ]
