# Generated by Django 5.0.6 on 2024-06-30 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_question_text_blogpost_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='text',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='content',
            field=models.TextField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
