# Generated by Django 5.0.6 on 2024-07-01 15:34

import mdeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_blogpost_text_blogpost_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=mdeditor.fields.MDTextField(),
        ),
    ]
