# Generated by Django 5.0.6 on 2024-07-01 22:40

import mdeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_blogpost_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=mdeditor.fields.MDTextField(verbose_name='Контент'),
        ),
    ]
