[project]
name = "wokalek-site-django"
version = "1.0.0"
requires-python = "==3.14.3"
dependencies = [
    "django==6.0.2",
    "django-cleanup==9.0.0",
    "django-cors-headers==4.9.0",
    "django-environ==0.12.0",
    "django-imagefield==0.22.0",
    "django-mdeditor==0.1.20",
    "pillow==12.1.0",
    "pillow-avif-plugin==1.5.5",
    "psycopg-binary==3.3.2",
    "psycopg[binary,pool]==3.3.2",
    "strawberry-graphql[cli]==0.291.3",
    "strawberry-graphql-django==0.75.0",
]

[dependency-groups]
dev = [
    "autopep8==2.3.2",
    "debugpy==1.8.20",
]
prod = [
    "hypercorn==0.18.0",
]

[tool.poe.tasks]
format.shell = "find -type f -name '*.py' ! -path '*/migrations/*' -exec autopep8 -i -a '{}' \\;"
outdated = "uv pip list --outdated"
check = "./manage.py check"
check-deploy = "./manage.py check --deploy"
collectstatic = "./manage.py collectstatic"
makemigrations = "./manage.py makemigrations"
migrate = "./manage.py migrate"
runserver = "./manage.py runserver"
dev.sequence = ["makemigrations", "migrate", "runserver"]
process_imagefields = "./manage.py process_imagefields --all"
