[project]
name = "wokalek-site-django"
version = "1.0.0"
requires-python = "==3.14.3"
dependencies = [
    "django==6.0.2",
    "django-cleanup==9.0.0",
    "django-cors-headers==4.9.0",
    "django-environ==0.12.0",
    "django-imagefield==0.22.0",
    "django-mdeditor==0.1.20",
    "pillow==12.1.0",
    "pillow-avif-plugin==1.5.5",
    "psycopg-binary==3.3.2",
    "psycopg[binary,pool]==3.3.2",
    "strawberry-graphql[cli]==0.291.3",
    "strawberry-graphql-django==0.75.0",
]

[dependency-groups]
dev = [
    "debugpy==1.8.20",
    "ruff==0.15.0",
]
prod = [
    "hypercorn==0.18.0",
]

[tool.poe.tasks]
lint = "ruff check"
format = "ruff format"
outdated = "uv pip list --outdated"
check = "./manage.py check"
check-deploy = "./manage.py check --deploy"
export-schema = "./manage.py export_schema api.schema --path schema.graphql"
process_imagefields = "./manage.py process_imagefields --all"

[tool.ruff]
extend-exclude = ["migrations"]

[tool.ruff.format]
quote-style = "single"

[tool.ruff.lint.per-file-ignores]
"app/settings/__init__.py" = ["F403"]
