[project]
name = "wokalek-site-django"
version = "1.0.0"
requires-python = "==3.12.5"
dependencies = [
    "django==6.0.2",
    "django-cleanup==8.1.0",
    "django-cors-headers==4.4.0",
    "django-environ==0.11.2",
    "django-imagefield==0.19.1",
    "django-mdeditor==0.1.20",
    "pillow==10.4.0",
    "pillow-avif-plugin==1.4.6",
    "psycopg[binary,pool]==3.2.1",
    "strawberry-graphql==0.237.3",
    "strawberry-graphql-django==0.47.1",
]

[dependency-groups]
dev = [
    "autopep8==2.3.1",
    "debugpy==1.8.5",
]
prod = [
    "hypercorn==0.17.3",
]

[tool.poe.tasks]
format.shell = "find -type f -name '*.py' ! -path '*/migrations/*' -exec autopep8 -i -a '{}' \\;"
outdated = "uv pip list --outdated"
check = "./manage.py check"
check-deploy = "./manage.py check --deploy"
collectstatic = "./manage.py collectstatic"
makemigrations = "./manage.py makemigrations"
migrate = "./manage.py migrate"
runserver = "./manage.py runserver"
dev.sequence = ["makemigrations", "migrate", "runserver"]
process_imagefields = "./manage.py process_imagefields --all"
