# Generated by Django 5.0.7 on 2024-07-11 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'статью', 'verbose_name_plural': 'статьи'},
        ),
    ]
