# Generated by Django 5.0.7 on 2024-07-11 19:05

from django.db import migrations, models
import uuid

from articles.models import Article


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_article_options'),
    ]

    def gen_uuid(apps, schema_editor):
        for row in Article.objects.all():
            row.slug = uuid.uuid4()
            row.save()

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(default=uuid.uuid4, verbose_name='Человекопонятный URL'),
            preserve_default=False,
        ),

        migrations.RunPython(gen_uuid),

        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(default=uuid.uuid4, unique=True, verbose_name='Человекопонятный URL'),
        ),
    ]
